### ISSUE TITLE
能否尽快更新自定义动作？

### ISSUE THREAD

**Issue by 2568754202** [binary-husky/unreal-map#1]
感谢你们的工作，顺利测试了你们的案例，但是没有自定义动作的介绍，没有办法自主开发一些其它案例啊，急切期盼尽快更新。谢谢

**Comment by binary-husky** [comment]
感谢支持，我们尽快更新案例

**Comment by binary-husky** [comment]
> 感谢你们的工作，顺利测试了你们的案例，但是没有自定义动作的介绍，没有办法自主开发一些其它案例啊，急切期盼尽快更新。谢谢

感谢支持，我们尽快更新案例

**Comment by binary-husky** [comment]
We have updated tutorial ppt in master branch, with steps to design custom actions
