### ISSUE TITLE
在打开uhmp.uproject  switch UE引擎选了源码的4.27之后出现错误

### ISSUE THREAD

**Issue by ShiXiangnan** [binary-husky/unreal-map#7]
![image](https://github.com/binary-husky/unreal-map/assets/42862589/d8674b0a-c8cc-4222-8685-9ca002ba7211)
Running F:/programs/UnrealEngine-4.27/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="F:/programs/unreal_map/unreal-map/UHMP.uproject" -game -engine -progress -log="F:\programs\unreal_map\unreal-map/Saved/Logs/UnrealVersionSelector-Win64-Shipping-2023.06.21-14.18.33.log"
Discovering modules, targets and source code for project...
While compiling F:\programs\unreal_map\unreal-map\Intermediate\Build\BuildRules\UHMPModuleRules.dll:
error CS0042: ??????????Ϣ?ļ???f:\programs\unreal_map\unreal-map\Intermediate\Build\BuildRules\UHMPModuleRules.PDB??ʱ???????? --??δָ???Ĵ??? ??
ERROR: Unable to compile source files.
这是什么情况啊……在打开uhmp.uproject  switch UE引擎选了源码的4.27之后就这样了

**Comment by binary-husky** [comment]
是否使用视频中的步骤`https://ageasga-my.sharepoint.com/:v:/g/personal/fuqingxu_yiteam_tech/EawfqsV2jF5Nsv3KF7X1-woBH-VTvELL6FSRX4cIgUboLg?e=Vmp67E`编译虚幻引擎的源码呢

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ShiXiangnan** [comment]
> 是否使用视频中的步骤`https://ageasga-my.sharepoint.com/:v:/g/personal/fuqingxu_yiteam_tech/EawfqsV2jF5Nsv3KF7X1-woBH-VTvELL6FSRX4cIgUboLg?e=Vmp67E`编译虚幻引擎的源码呢

已经解决，感谢回复！

**Comment by Tinysimpler** [comment]
> > 是否使用视频中的步骤`https://ageasga-my.sharepoint.com/:v:/g/personal/fuqingxu_yiteam_tech/EawfqsV2jF5Nsv3KF7X1-woBH-VTvELL6FSRX4cIgUboLg?e=Vmp67E`编译虚幻引擎的源码呢
> 
> 已经解决，感谢回复！

在下也遇到了，请教大侠如何解决是好？

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
